version: "3.8"

services:
  pytorch-container:
    image: nvcr.io/nvidia/pytorch:24.05-py3 
    runtime: nvidia
    #privileged: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            #- capabilities: [gpu]
            - capabilities: 
              - gpu
              - utility
              #- compute
              driver: nvidia
              count: all
    devices:
      - "/dev/nvidia0:/dev/nvidia0"
      - "/dev/nvidia1:/dev/nvidia1"
      - "/dev/nvidia2:/dev/nvidia2"
      - "/dev/nvidia3:/dev/nvidia3"
      - "/dev/nvidiactl:/dev/nvidiactl"
      - "/dev/nvidia-uvm:/dev/nvidia-uvm"
      - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    command:
      - nvidia-smi
    #   HOME: ${HOME}
    #   USER: ${USER}
    # volumes:
    #   - ${HOME}:${HOME}
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   stack:
    #     soft: 67108864
    #     hard: 67108864
    #stdin_open: true  # Equivalent to `-i` in `docker run`
    #tty: true         # Equivalent to `-t` in `docker run`
